//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Molinos.Orquest.DriversImpl.ServicioALPR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoComando", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoCancelarSuscripcion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoSuscribir))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoBorrarBalanzadasPorRango))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoConsultaBalanzadaPorRango))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoConsultaBalanzada))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoBorrarBalanzada))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoMeteorologica))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoTomarFoto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoObtenerPatente))]
    public partial class ResultadoComando : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Molinos.Orquest.DriversImpl.ServicioALPR.Mensaje MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Molinos.Orquest.DriversImpl.ServicioALPR.Mensaje Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoCancelarSuscripcion", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoCancelarSuscripcion : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoComando {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoSuscribir", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoSuscribir : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoComando {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSuscripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSuscripcion {
            get {
                return this.IdSuscripcionField;
            }
            set {
                if ((this.IdSuscripcionField.Equals(value) != true)) {
                    this.IdSuscripcionField = value;
                    this.RaisePropertyChanged("IdSuscripcion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoEjecutar", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoBorrarBalanzadasPorRango))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoConsultaBalanzadaPorRango))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoConsultaBalanzada))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoBorrarBalanzada))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoMeteorologica))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoTomarFoto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoObtenerPatente))]
    public partial class ResultadoEjecutar : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoComando {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, decimal> ValoresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, decimal> Valores {
            get {
                return this.ValoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresField, value) != true)) {
                    this.ValoresField = value;
                    this.RaisePropertyChanged("Valores");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoBorrarBalanzadasPorRango", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoBorrarBalanzadasPorRango : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdBalanzadaInicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBalanzadaInicio {
            get {
                return this.IdBalanzadaInicioField;
            }
            set {
                if ((this.IdBalanzadaInicioField.Equals(value) != true)) {
                    this.IdBalanzadaInicioField = value;
                    this.RaisePropertyChanged("IdBalanzadaInicio");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoConsultaBalanzadaPorRango", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoConsultaBalanzadaPorRango : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoConsultaBalanzada[] BalanzadasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoConsultaBalanzada[] Balanzadas {
            get {
                return this.BalanzadasField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanzadasField, value) != true)) {
                    this.BalanzadasField = value;
                    this.RaisePropertyChanged("Balanzadas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoConsultaBalanzada", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoConsultaBalanzada : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ValoresBalanzadaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ValoresBalanzada {
            get {
                return this.ValoresBalanzadaField;
            }
            set {
                if ((object.ReferenceEquals(this.ValoresBalanzadaField, value) != true)) {
                    this.ValoresBalanzadaField = value;
                    this.RaisePropertyChanged("ValoresBalanzada");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoBorrarBalanzada", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoBorrarBalanzada : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoMeteorologica", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoMeteorologica : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Molinos.Orquest.DriversImpl.ServicioALPR.MeteorologicaDto[] ImagenesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Molinos.Orquest.DriversImpl.ServicioALPR.MeteorologicaDto[] Imagenes {
            get {
                return this.ImagenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenesField, value) != true)) {
                    this.ImagenesField = value;
                    this.RaisePropertyChanged("Imagenes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoTomarFoto", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoTomarFoto : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoObtenerPatente", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Resultados")]
    [System.SerializableAttribute()]
    public partial class ResultadoObtenerPatente : Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoEjecutar {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ConfianzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatenteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Confianza {
            get {
                return this.ConfianzaField;
            }
            set {
                if ((this.ConfianzaField.Equals(value) != true)) {
                    this.ConfianzaField = value;
                    this.RaisePropertyChanged("Confianza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patente {
            get {
                return this.PatenteField;
            }
            set {
                if ((object.ReferenceEquals(this.PatenteField, value) != true)) {
                    this.PatenteField = value;
                    this.RaisePropertyChanged("Patente");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeteorologicaDto", Namespace="http://schemas.datacontract.org/2004/07/Molinos.Orquest.Dominio.Dtos")]
    [System.SerializableAttribute()]
    public partial class MeteorologicaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[][] ImagenesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[][] Imagenes {
            get {
                return this.ImagenesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenesField, value) != true)) {
                    this.ImagenesField = value;
                    this.RaisePropertyChanged("Imagenes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://orquestador.molinos.com.ar", ConfigurationName="ServicioALPR.IServicioALPR")]
    public interface IServicioALPR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://orquestador.molinos.com.ar/IServicioALPR/LeerPatente", ReplyAction="http://orquestador.molinos.com.ar/IServicioALPR/LeerPatenteResponse")]
        Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoObtenerPatente LeerPatente(byte[] imagen, int margenIzquierdo, int margenDerecho, int margenSuperior, int margenInferior);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://orquestador.molinos.com.ar/IServicioALPR/LeerPatente", ReplyAction="http://orquestador.molinos.com.ar/IServicioALPR/LeerPatenteResponse")]
        System.Threading.Tasks.Task<Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoObtenerPatente> LeerPatenteAsync(byte[] imagen, int margenIzquierdo, int margenDerecho, int margenSuperior, int margenInferior);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioALPRChannel : Molinos.Orquest.DriversImpl.ServicioALPR.IServicioALPR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioALPRClient : System.ServiceModel.ClientBase<Molinos.Orquest.DriversImpl.ServicioALPR.IServicioALPR>, Molinos.Orquest.DriversImpl.ServicioALPR.IServicioALPR {
        
        public ServicioALPRClient() {
        }
        
        public ServicioALPRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioALPRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioALPRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioALPRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoObtenerPatente LeerPatente(byte[] imagen, int margenIzquierdo, int margenDerecho, int margenSuperior, int margenInferior) {
            return base.Channel.LeerPatente(imagen, margenIzquierdo, margenDerecho, margenSuperior, margenInferior);
        }
        
        public System.Threading.Tasks.Task<Molinos.Orquest.DriversImpl.ServicioALPR.ResultadoObtenerPatente> LeerPatenteAsync(byte[] imagen, int margenIzquierdo, int margenDerecho, int margenSuperior, int margenInferior) {
            return base.Channel.LeerPatenteAsync(imagen, margenIzquierdo, margenDerecho, margenSuperior, margenInferior);
        }
    }
}
